### ISSUE TITLE
ReaderTask loop is too slow

### ISSUE THREAD

**Issue by k5123** [JTrotta/SerialPortLib2#4]
I'm trying to read messages from a serial connection that sends small messages quite rapidly. The 100ms wait in your reader loop will prevent (near) real time messaging. In my opinion this should be reduced drastically or removed altogether.

For testing purposes i set it to two (Line 296 of SerialPortInput), and CPU usage didn't change.

**Comment by JTrotta** [comment]
@whiten01se So you suggest to change it from 100 ms to 2 ms?
Did you tested it at 2 ms?

**Comment by k5123** [comment]
I tested it with no delay at all, actually, and i got nice realtime responsiveness out of it. CPU usage isn't more than before.

**Comment by JTrotta** [comment]
Good!
Than I will set it as a parameter, with 100 by default, so anyone can decide the right value.
Many thanks

**Comment by k5123** [comment]
Yep, parametrization is even better. Didn't think of that :)

**Comment by JTrotta** [comment]
Done

**Comment by k5123** [comment]
Just one more thing [tm]:

 SerialPortInput.cs | 3 ++-
 1 file changed, 2 insertions(+), 1 deletion(-)

diff --git a/SerialPortInput.cs b/SerialPortInput.cs
index dcecdf3..72a57f5 100644
--- a/SerialPortInput.cs
+++ b/SerialPortInput.cs
@@ -142,7 +142,7 @@ public bool IsConnected
         /// </summary>
         /// <param name="portname">Portname.</param>
         /// <param name="baudrate">Baudrate.</param>
-        public void SetPort(string portname, int baudrate = 115200, Handshake handshake = Handshake.None)
+        public void SetPort(string portname, int baudrate = 115200, Handshake handshake = Handshake.None, int readerTaskTime = 100)
         {
             if (!string.IsNullOrEmpty(_portName) && _portName != portname)
             {
@@ -153,6 +153,7 @@ public void SetPort(string portname, int baudrate = 115200, Handshake handshake
             _portName = portname;
             _defaultBaudRate = baudrate;
             _handshake = handshake;
+            _readerTaskTimeWait = readerTaskTime;
         }

**Comment by JTrotta** [comment]
done
