### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by cschweers** [JTrotta/SerialPortLib2#5]
This repository should contain a license file
https://help.github.com/articles/licensing-a-repository/

This would help to clarify if and how other users are allowed to use this library in private/commercial projects

**Comment by JTrotta** [comment]
Thank you.

**Comment by cschweers** [comment]
Thank you very much @JTrotta for the quick Implementation! Maybe it would also be great to update the corresponding NuGet package. That was the root cause why I ended up here :relaxed:
