### ISSUE TITLE
create virtual serial port device in Win10

### ISSUE THREAD

**Issue by davesliu** [JTrotta/SerialPortLib2#8]
@JTrotta 

Thanks for your share of MonoSerialPort.
Is it possible to use this library to create virtual serial port device ? Just like the Virtual COM Port Driver tool on Win10?

**Comment by JTrotta** [comment]
Really, I do not know.
This library is specific to be used on Linux and Mono/dotnetcore, where there is a problem initializing virtual ports. I only added the Linux SerialPortStream.cs, modifying WinPortStrem.cs. The windows code is exactly the same.
You can try on Win10. 
I will be happy to make changes.

**Comment by davesliu** [comment]
thanks for your comments, I had tried com0com to created virtual serial port but it can not be parsed by pyserial,  we decided to buy VSPD
